### ISSUE TITLE
Updating Casefile fails

### ISSUE THREAD

**Issue by ahmadnazir** [Penneo/sdk-php#6]
Updating a casefile or even persisting the same casefile twice fails. The following code snippet fails to execute:

```
$myCaseFile = new Penneo\CaseFile();
$myCaseFile->setTitle('Demo case file');
Penneo\CaseFile::persist($myCaseFile);
Penneo\CaseFile::persist($myCaseFile);
```

The exception thrown is:

```
Stack trace:
#0 /vagrant/src/Util/CaseFileManager.php(15): Penneo\SDK\Entity::persist(Object(Penneo\SDK\CaseFile))
#1 /vagrant/src/run.php(29): Util\CaseFileManager->create()
#2 {main}
  thrown in /vagrant/vendor/penneo/penneo-sdk-php/src/Entity.php on line 212
```

This is because the visibilityMode is not set for the casefile when it is updated.

**Comment by ahmadnazir** [comment]
This is caused due to Penneo/Symfony2#384
